In [20]:
import array as arr
list = [2,8,7,11]
Q1 = arr.array('i', list)
Q1

array('i', [2, 8, 7, 11])

In [28]:
import numpy as np
Q2 = np.array([[1, 2, 3], 
      [4, 5, 6], 
      [7, 8, 9]])

print(Q2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
Q3 = Q2[ :, 1:2]
print(Q3)

In [ ]:
np.random.seed(6)
Q4 = np.random.randint(9, size = (6,5))
Q4

In [ ]:
Q5 = Q4[:3, :2]
print(Q5)